In [9]:
from EvalAndLoss import onehot2index
import torch
onehot = torch.randn(3,4,2,2)
print(onehot)
print(onehot.shape)
index = onehot2index(onehot)
print(index)
print(index.shape)

tensor([[[[-1.2770, -0.0365],
          [ 0.8504, -0.7955]],

         [[ 0.3952, -3.0420],
          [-1.3678, -0.3908]],

         [[ 1.3928, -0.3926],
          [ 0.3143,  0.3294]],

         [[ 1.0659,  0.0909],
          [-1.7372,  0.5128]]],


        [[[-0.6215, -0.9318],
          [-1.7554, -0.2766]],

         [[ 0.5350, -0.2120],
          [ 0.2825, -0.1146]],

         [[ 1.2075, -0.9873],
          [-1.2648, -1.0124]],

         [[ 0.1733,  1.5250],
          [-1.2210, -1.4409]]],


        [[[ 0.2667, -2.1353],
          [ 0.3502,  1.4354]],

         [[-0.8154,  1.2190],
          [ 0.9452, -1.2289]],

         [[-0.3375, -1.1769],
          [-0.5800,  0.4827]],

         [[ 0.8081, -0.7388],
          [ 0.8396,  1.0868]]]])
torch.Size([3, 4, 2, 2])
tensor([[[[2, 3],
          [0, 3]]],


        [[[2, 3],
          [1, 1]]],


        [[[3, 1],
          [1, 0]]]])
torch.Size([3, 1, 2, 2])


In [10]:
import torch

# 假设输出一个 [batch_size=2, channel=1, height=2, width=2] 格式的张量 x1
x1 = torch.tensor(
    [[[[ 0.43, -0.25],
        [-0.32, 0.69]]],

        [[[-0.29, 0.37],
          [0.54,  -0.72]]]])

# 假设标签图像为与 x1 同型的张量 y1
y1 = torch.tensor(
    [[[[0., 0.],
        [0., 1.]]],

        [[[0., 0.],
          [1.,  1.]]]])
print(x1.shape)

torch.Size([2, 1, 2, 2])


In [11]:
s1 = torch.sigmoid(x1)
s1

tensor([[[[0.6059, 0.4378],
          [0.4207, 0.6660]]],


        [[[0.4280, 0.5915],
          [0.6318, 0.3274]]]])

In [12]:
# 2.交叉熵计算
loss_cal = -1*(y1*torch.log(s1)+(1-y1)*torch.log(1-s1)) # 此处相当于一个one-hot编码
print(loss_cal.shape)
print(loss_cal)
loss_cal_mean = torch.mean(loss_cal)
loss_cal_mean

torch.Size([2, 1, 2, 2])
tensor([[[[0.9311, 0.5759],
          [0.5459, 0.4065]]],


        [[[0.5586, 0.8952],
          [0.4592, 1.1166]]]])


tensor(0.6861)

In [13]:
# 假设输出一个[batch_size=2, channel=2, height=2, width=2]格式的张量 x1
x1 = torch.tensor([[[[ 0.3164, -0.1922],
          [ 0.4326, -1.2193]],

         [[ 0.6873,  0.6838],
          [ 0.2244,  0.5615]]],


        [[[-0.2516, -0.8875],
          [-0.6289, -0.1796]],

         [[ 0.0411, -1.7851],
          [-0.3069, -1.0379]]]])

# 假设标签图像为与x1同型，然后去掉channel的张量 y1 （注意两点，channel没了，格式为LongTensor）
y1 = torch.LongTensor([[[0., 1.],
         [1., 0.]],

        [[1., 1.],
         [0., 1.]]])
y1_one_hot = torch.zeros_like(x1).scatter_(dim=1,index=y1.unsqueeze(dim=1),src=torch.ones_like(x1))
y1_one_hot
print(y1_one_hot.shape)

torch.Size([2, 2, 2, 2])


/tmp/ipykernel_4113/3830234296.py:16: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  y1 = torch.LongTensor([[[0., 1.],


In [14]:
loss_ce = torch.nn.CrossEntropyLoss(reduction='none')(x1,y1)
print(loss_ce)
from eval_loss import *
loss_my = CrossEntropyLoss()(x1,y1_one_hot)
focal = FocalLoss(gamma=1,reduction='none')(x1,y1_one_hot)
print(focal)

tensor([[[0.8957, 0.3482],
         [0.8027, 1.9365]],

        [[0.5575, 1.2394],
         [0.8671, 1.2117]]])
tensor([[[0.5300, 0.1024],
         [0.4430, 1.6573]],

        [[0.2382, 0.8806],
         [0.5027, 0.8510]]])


In [15]:
# test Dice loss
x1 = torch.tensor([[[[ 0.3164, -0.1922],
          [ 0.4326, -1.2193]],

         [[ 0.6873,  0.6838],
          [ 0.2244,  0.5615]]],


        [[[-0.2516, -0.8875],
          [-0.6289, -0.1796]],

         [[ 0.0411, -1.7851],
          [-0.3069, -1.0379]]]])
# 假设标签图像为与x1同型，然后去掉channel的张量 y1 （注意两点，channel没了，格式为LongTensor）
y1 = torch.LongTensor([[[0., 1.],
         [1., 0.]],

        [[1., 1.],
         [0., 1.]]])
y1_one_hot = torch.zeros_like(x1).scatter_(dim=1,index=y1.unsqueeze(dim=1),src=torch.ones_like(x1))
print(y1_one_hot)

tensor([[[[1., 0.],
          [0., 1.]],

         [[0., 1.],
          [1., 0.]]],


        [[[0., 0.],
          [1., 0.]],

         [[1., 1.],
          [0., 1.]]]])


/tmp/ipykernel_4113/2040371511.py:15: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  y1 = torch.LongTensor([[[0., 1.],


In [22]:
dice = BinaryDiceLoss(reduction='mean')
predict = torch.nn.functional.softmax(x1,dim=1)
print(predict[:,0])
print(y1_one_hot[:,0])
loss = dice(predict[:,0],y1_one_hot[:,0])
print(loss)
print(loss.shape)

tensor([[[0.4083, 0.2940],
         [0.5519, 0.1442]],

        [[0.4273, 0.7105],
         [0.4202, 0.7023]]])
tensor([[[1., 0.],
         [0., 1.]],

        [[0., 0.],
         [1., 0.]]])
tensor(0.5447)
torch.Size([])
