In [1]:
from datasets import *
types = ['SysLGE']
data = load_image(str=types,paired_label=False)

In [2]:
image = data['image']
#label = data['label']
print(len(image))
#print(len(label))

176


In [3]:
from EvalAndLoss import onehot2index
import torch
onehot = torch.randn(3,4,2,2)
print(onehot)
print(onehot.shape)
index = onehot2index(onehot)
print(index)
print(index.shape)

tensor([[[[ 1.0093, -0.3021],
          [-0.4169, -1.9653]],

         [[-0.1823, -1.1946],
          [ 0.2202, -2.9782]],

         [[-0.7327,  0.1997],
          [ 0.3674,  0.4323]],

         [[-1.1173, -1.2745],
          [ 0.3976, -1.8637]]],


        [[[-0.9157, -0.3130],
          [ 0.4990,  0.1755]],

         [[ 1.5024,  0.5060],
          [ 0.5320,  0.0626]],

         [[ 2.4434, -0.6025],
          [-0.3903, -2.2550]],

         [[-1.4549, -0.2058],
          [-1.8740, -1.0768]]],


        [[[ 1.6916,  0.6176],
          [ 2.6820, -1.1039]],

         [[ 0.1656,  1.0228],
          [-0.0164,  0.6190]],

         [[-0.6410,  1.4568],
          [ 0.3564, -1.3673]],

         [[ 1.0124, -0.0052],
          [ 0.0876,  0.3646]]]])
torch.Size([3, 4, 2, 2])
tensor([[[[0, 2],
          [3, 2]]],


        [[[2, 1],
          [1, 0]]],


        [[[0, 2],
          [0, 1]]]])
torch.Size([3, 1, 2, 2])


In [4]:
import torch

# 假设输出一个 [batch_size=2, channel=1, height=2, width=2] 格式的张量 x1
x1 = torch.tensor(
    [[[[ 0.43, -0.25],
        [-0.32, 0.69]]],

        [[[-0.29, 0.37],
          [0.54,  -0.72]]]])

# 假设标签图像为与 x1 同型的张量 y1
y1 = torch.tensor(
    [[[[0., 0.],
        [0., 1.]]],

        [[[0., 0.],
          [1.,  1.]]]])
print(x1.shape)

torch.Size([2, 1, 2, 2])


In [5]:
s1 = torch.sigmoid(x1)
s1

tensor([[[[0.6059, 0.4378],
          [0.4207, 0.6660]]],


        [[[0.4280, 0.5915],
          [0.6318, 0.3274]]]])

In [6]:
# 2.交叉熵计算
loss_cal = -1*(y1*torch.log(s1)+(1-y1)*torch.log(1-s1)) # 此处相当于一个one-hot编码
print(loss_cal.shape)
print(loss_cal)
loss_cal_mean = torch.mean(loss_cal)
loss_cal_mean

torch.Size([2, 1, 2, 2])
tensor([[[[0.9311, 0.5759],
          [0.5459, 0.4065]]],


        [[[0.5586, 0.8952],
          [0.4592, 1.1166]]]])


tensor(0.6861)

In [11]:
# 假设输出一个[batch_size=2, channel=2, height=2, width=2]格式的张量 x1
x1 = torch.tensor([[[[ 0.3164, -0.1922],
          [ 0.4326, -1.2193]],

         [[ 0.6873,  0.6838],
          [ 0.2244,  0.5615]]],


        [[[-0.2516, -0.8875],
          [-0.6289, -0.1796]],

         [[ 0.0411, -1.7851],
          [-0.3069, -1.0379]]]])

# 假设标签图像为与x1同型，然后去掉channel的张量 y1 （注意两点，channel没了，格式为LongTensor）
y1 = torch.LongTensor([[[0., 1.],
         [1., 0.]],

        [[1., 1.],
         [0., 1.]]])
y1_one_hot = torch.zeros_like(x1).scatter_(dim=1,index=y1.unsqueeze(dim=1),src=torch.ones_like(x1))
y1_one_hot
print(y1_one_hot.shape)

torch.Size([2, 2, 2, 2])


/tmp/ipykernel_2498/3830234296.py:16: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  y1 = torch.LongTensor([[[0., 1.],


In [35]:
loss_ce = torch.nn.CrossEntropyLoss(reduction='none')(x1,y1)
print(loss_ce)
from EvalAndLoss import *
loss_my = CrossEntropyLoss()(x1,y1_one_hot)
focal = FocalLoss(gamma=1,reduction='none')(x1,y1_one_hot)
print(focal)

tensor([[[0.8957, 0.3482],
         [0.8027, 1.9365]],

        [[0.5575, 1.2394],
         [0.8671, 1.2117]]])
tensor([[[0.5300, 0.1024],
         [0.4430, 1.6573]],

        [[0.2382, 0.8806],
         [0.5027, 0.8510]]])


In [5]:
import numpy as np
from predict import mean_std
a = [[1,-1,2],[0,1,1]]
b = mean_std(a)
print(b)
np.mean(b[:,0])

[[0.5 0.5]
 [1.  0. ]
 [1.5 0.5]]


1.0

In [15]:
from datasets import load_image
types = ['SysLGE']
need_data = load_image(str=types,paired_label=True)
image = need_data['image']
label = need_data['label']
for i in range(0,len(image)):
    print(f'image:{image[i].shape},label:{label[i].shape}')

image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(320, 320)
image:(256, 256),label:(320, 320)
image:(256, 256),label:(320, 320)
image:(256, 256),label:(320, 320)
image:(256, 256),label:(320, 320)
image:(320, 320),label:(320, 320)
image:(320, 320),label:(320, 320)
image:(320, 320),label:(320, 320)
image:(320, 320),label:(320, 320)
image:(320, 320),label:(320, 320)
image:(320, 320),label:(320, 320)
image:(320, 320),label:(256, 256)
image:(320, 320),label:(256, 256)
image:(320, 320),label:(256, 256)
image:(320, 320),label:(256, 256)
image:(320, 320),label:(256, 256)
image:(320, 320),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(256, 256)
image:(256, 256),label:(320, 320)
image:(256, 25